# Generated by Django 4.1.7 on 2023-03-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='RecipeIngredient',
        ),
    ]
